-- IntraTech PC Builder - esquema PostgreSQL para Supabase
-- Execute este arquivo inteiro no SQL Editor de um projeto Supabase vazio.

BEGIN;

CREATE TABLE IF NOT EXISTS public.usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    login VARCHAR(80) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL DEFAULT 'USUARIO',
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('ADMIN', 'USUARIO'))
);

CREATE TABLE IF NOT EXISTS public.processador (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    socket VARCHAR(30) NOT NULL,
    consumo INTEGER NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    fabricante VARCHAR(80) NOT NULL,
    nucleos INTEGER NOT NULL,
    threads INTEGER NOT NULL,
    desempenho NUMERIC(10, 2) NOT NULL,
    CONSTRAINT ck_processador_valores CHECK (
        consumo >= 0 AND preco >= 0 AND nucleos > 0 AND threads > 0 AND desempenho > 0
    )
);

CREATE TABLE IF NOT EXISTS public.placa_mae (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    fabricante VARCHAR(80) NOT NULL,
    socket VARCHAR(30) NOT NULL,
    tipo_memoria VARCHAR(20) NOT NULL,
    consumo INTEGER NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_placa_mae_valores CHECK (consumo >= 0 AND preco >= 0)
);

CREATE TABLE IF NOT EXISTS public.placa_video (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    fabricante VARCHAR(80) NOT NULL,
    memoria INTEGER NOT NULL,
    consumo INTEGER NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    desempenho INTEGER NOT NULL,
    CONSTRAINT ck_placa_video_valores CHECK (
        memoria > 0 AND consumo >= 0 AND preco >= 0 AND desempenho > 0
    )
);

CREATE TABLE IF NOT EXISTS public.memoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    capacidade INTEGER NOT NULL,
    frequencia INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_memoria_valores CHECK (capacidade > 0 AND frequencia > 0 AND preco >= 0)
);

CREATE TABLE IF NOT EXISTS public.ssd (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    capacidade INTEGER NOT NULL,
    leitura INTEGER NOT NULL,
    escrita INTEGER NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_ssd_valores CHECK (
        capacidade > 0 AND leitura > 0 AND escrita > 0 AND preco >= 0
    )
);

CREATE TABLE IF NOT EXISTS public.fonte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    potencia INTEGER NOT NULL,
    certificacao VARCHAR(60) NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_fonte_valores CHECK (potencia > 0 AND preco >= 0)
);

CREATE TABLE IF NOT EXISTS public.jogo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    exigencia_cpu INTEGER NOT NULL,
    exigencia_gpu INTEGER NOT NULL,
    genero VARCHAR(60),
    descricao VARCHAR(500),
    imagem_url VARCHAR(1000),
    CONSTRAINT ck_jogo_valores CHECK (exigencia_cpu > 0 AND exigencia_gpu > 0)
);

CREATE TABLE IF NOT EXISTS public.build (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES public.usuario(id),
    processador_id INTEGER NOT NULL REFERENCES public.processador(id),
    placa_mae_id INTEGER NOT NULL REFERENCES public.placa_mae(id),
    placa_video_id INTEGER NOT NULL REFERENCES public.placa_video(id),
    memoria_id INTEGER NOT NULL REFERENCES public.memoria(id),
    ssd_id INTEGER NOT NULL REFERENCES public.ssd(id),
    fonte_id INTEGER NOT NULL REFERENCES public.fonte(id),
    favorita BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.benchmark_fps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogo_id INTEGER NOT NULL REFERENCES public.jogo(id),
    processador_id INTEGER NOT NULL REFERENCES public.processador(id),
    placa_video_id INTEGER NOT NULL REFERENCES public.placa_video(id),
    resolucao VARCHAR(20) NOT NULL,
    qualidade VARCHAR(20) NOT NULL,
    fps_medio INTEGER NOT NULL,
    fps_1_low INTEGER,
    fonte VARCHAR(255) NOT NULL,
    observacoes VARCHAR(255),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_benchmark_fps_medio CHECK (fps_medio > 0),
    CONSTRAINT ck_benchmark_fps_1_low CHECK (
        fps_1_low IS NULL OR (fps_1_low > 0 AND fps_1_low <= fps_medio)
    )
);

CREATE TABLE IF NOT EXISTS public.componente_importado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL,
    componente_id INTEGER NOT NULL,
    origem VARCHAR(40) NOT NULL,
    id_externo VARCHAR(120) NOT NULL,
    nome_original VARCHAR(255) NOT NULL,
    importado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_componente_importado UNIQUE (tipo, origem, id_externo)
);

CREATE INDEX IF NOT EXISTS idx_build_usuario ON public.build(usuario_id);
CREATE INDEX IF NOT EXISTS idx_build_usuario_favorita ON public.build(usuario_id, favorita);
CREATE INDEX IF NOT EXISTS idx_benchmark_busca
    ON public.benchmark_fps(jogo_id, placa_video_id, processador_id, resolucao, qualidade);
CREATE INDEX IF NOT EXISTS idx_benchmark_recomendacao
    ON public.benchmark_fps(jogo_id, resolucao, fps_medio);

INSERT INTO public.jogo (nome, exigencia_cpu, exigencia_gpu)
VALUES
    ('Counter-Strike 2', 70, 65),
    ('Cyberpunk 2077', 85, 95),
    ('Fortnite', 60, 60)
ON CONFLICT (nome) DO NOTHING;

-- A aplicação atual acessa o PostgreSQL por JDBC. A Data API pública não deve
-- conseguir ler as senhas ou alterar as tabelas usando apenas uma API key.
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.processador ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.placa_mae ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.placa_video ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ssd ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fonte ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.build ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.benchmark_fps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.componente_importado ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
    public.usuario,
    public.processador,
    public.placa_mae,
    public.placa_video,
    public.memoria,
    public.ssd,
    public.fonte,
    public.jogo,
    public.build,
    public.benchmark_fps,
    public.componente_importado
FROM anon, authenticated;

COMMIT;
