import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseMigrationService {

    public void aplicar() {
        try (Connection connection = ConnectionFactory.getConexao()) {
            if (!colunaPerfilExiste(connection)) {
                try (Statement statement = connection.createStatement()) {
                    statement.executeUpdate("""
                            ALTER TABLE usuario
                            ADD COLUMN perfil VARCHAR(20) NOT NULL DEFAULT 'USUARIO'
                            """);
                }
            }

            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("""
                        UPDATE usuario
                        SET perfil = 'USUARIO'
                        WHERE perfil IS NULL OR perfil NOT IN ('ADMIN', 'USUARIO')
                        """);
            }
            criarTabelaBenchmarks(connection);
            criarTabelaImportacoes(connection);
            adicionarColunaSeAusente(connection, "jogo", "genero", "VARCHAR(60) NULL");
            adicionarColunaSeAusente(connection, "jogo", "descricao", "VARCHAR(500) NULL");
            adicionarColunaSeAusente(connection, "jogo", "imagem_url", "VARCHAR(1000) NULL");
            criarIndiceRecomendacoes(connection);
        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível atualizar a estrutura do banco de dados.", e);
        }
    }

    private void criarTabelaBenchmarks(Connection connection) throws SQLException {
        String colunaId = colunaId(connection);
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS benchmark_fps (
                        id %s,
                        jogo_id INT NOT NULL,
                        processador_id INT NOT NULL,
                        placa_video_id INT NOT NULL,
                        resolucao VARCHAR(20) NOT NULL,
                        qualidade VARCHAR(20) NOT NULL,
                        fps_medio INT NOT NULL,
                        fps_1_low INT NULL,
                        fonte VARCHAR(255) NOT NULL,
                        observacoes VARCHAR(255) NULL,
                        criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_benchmark_jogo FOREIGN KEY (jogo_id) REFERENCES jogo(id),
                        CONSTRAINT fk_benchmark_processador FOREIGN KEY (processador_id) REFERENCES processador(id),
                        CONSTRAINT fk_benchmark_placa_video FOREIGN KEY (placa_video_id) REFERENCES placa_video(id),
                        CHECK (fps_medio > 0),
                        CHECK (fps_1_low IS NULL OR (fps_1_low > 0 AND fps_1_low <= fps_medio))
                    )
                    """.formatted(colunaId));
        }
    }

    private void criarTabelaImportacoes(Connection connection) throws SQLException {
        String colunaId = colunaId(connection);
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS componente_importado (
                        id %s,
                        tipo VARCHAR(30) NOT NULL,
                        componente_id INT NOT NULL,
                        origem VARCHAR(40) NOT NULL,
                        id_externo VARCHAR(120) NOT NULL,
                        nome_original VARCHAR(255) NOT NULL,
                        importado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT uk_componente_importado UNIQUE (tipo, origem, id_externo)
                    )
                    """.formatted(colunaId));
        }
    }

    private String colunaId(Connection connection) throws SQLException {
        String banco = connection.getMetaData().getDatabaseProductName().toLowerCase();
        return banco.contains("postgresql")
                ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                : "INT PRIMARY KEY AUTO_INCREMENT";
    }

    private void adicionarColunaSeAusente(
            Connection connection,
            String tabela,
            String coluna,
            String definicao
    ) throws SQLException {
        if (!colunaExiste(connection, tabela, coluna)) {
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("ALTER TABLE " + tabela + " ADD COLUMN " + coluna + " " + definicao);
            }
        }
    }

    private void criarIndiceRecomendacoes(Connection connection) throws SQLException {
        if (!indiceExiste(connection, "benchmark_fps", "idx_benchmark_recomendacao")) {
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("""
                        CREATE INDEX idx_benchmark_recomendacao
                        ON benchmark_fps(jogo_id, resolucao, fps_medio)
                        """);
            }
        }
    }

    private boolean indiceExiste(Connection connection, String tabela, String indice) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet indices = metadata.getIndexInfo(
                connection.getCatalog(),
                ConnectionFactory.isPostgreSQL() ? "public" : null,
                tabela,
                false,
                false
        )) {
            while (indices.next()) {
                String nome = indices.getString("INDEX_NAME");
                if (nome != null && nome.equalsIgnoreCase(indice)) {
                    return true;
                }
            }
            return false;
        }
    }

    private boolean colunaPerfilExiste(Connection connection) throws SQLException {
        return colunaExiste(connection, "usuario", "perfil");
    }

    private boolean colunaExiste(Connection connection, String tabela, String coluna) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        String catalogo = connection.getCatalog();
        String schema = ConnectionFactory.isPostgreSQL() ? "public" : null;
        try (ResultSet colunas = metadata.getColumns(catalogo, schema, tabela, coluna)) {
            return colunas.next();
        }
    }
}
