import model.Jogo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class JogoDAO {

    public void criarTabelaSeNaoExistir() {
        try (Connection con = ConnectionFactory.getConexao()) {
            String colunaId = con.getMetaData().getDatabaseProductName().toLowerCase().contains("postgresql")
                    ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                    : "INT PRIMARY KEY AUTO_INCREMENT";
            String sql = """
                    CREATE TABLE IF NOT EXISTS jogo (
                        id %s,
                        nome VARCHAR(100) NOT NULL UNIQUE,
                        exigencia_cpu INT NOT NULL,
                        exigencia_gpu INT NOT NULL,
                        genero VARCHAR(60) NULL,
                        descricao VARCHAR(500) NULL,
                        imagem_url VARCHAR(1000) NULL
                    )
                    """.formatted(colunaId);

            try (Statement stmt = con.createStatement()) {
                stmt.execute(sql);
            }
        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível preparar a tabela de jogos.", e);
        }
    }

    public void inserir(Jogo jogo) {
        criarTabelaSeNaoExistir();

        String sql = "INSERT INTO jogo (nome, exigencia_cpu, exigencia_gpu, genero, descricao, imagem_url) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection con = ConnectionFactory.getConexao();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, jogo.getNome());
            ps.setInt(2, jogo.getExigenciaCpu());
            ps.setInt(3, jogo.getExigenciaGpu());
            ps.setString(4, jogo.getGenero());
            ps.setString(5, jogo.getDescricao());
            ps.setString(6, jogo.getImagemUrl());

            ps.executeUpdate();

        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível cadastrar o jogo.", e);
        }
    }

    public void inserirNome(String nome) {
        inserirDetalhes(nome, null, null, null);
    }

    public void inserirDetalhes(String nome, String genero, String descricao, String imagemUrl) {
        criarTabelaSeNaoExistir();
        String sql = "INSERT INTO jogo (nome, exigencia_cpu, exigencia_gpu, genero, descricao, imagem_url) VALUES (?, 1, 1, ?, ?, ?)";

        try (Connection con = ConnectionFactory.getConexao();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, nome);
            ps.setString(2, vazioComoNull(genero));
            ps.setString(3, vazioComoNull(descricao));
            ps.setString(4, vazioComoNull(imagemUrl));
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível cadastrar o jogo.", e);
        }
    }

    public Jogo buscarPorId(int id) {
        criarTabelaSeNaoExistir();

        String sql = "SELECT * FROM jogo WHERE id = ?";

        try (Connection con = ConnectionFactory.getConexao();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Jogo jogo = new Jogo();
                jogo.setId(rs.getInt("id"));
                jogo.setNome(rs.getString("nome"));
                jogo.setExigenciaCpu(rs.getInt("exigencia_cpu"));
                jogo.setExigenciaGpu(rs.getInt("exigencia_gpu"));
                jogo.setGenero(rs.getString("genero"));
                jogo.setDescricao(rs.getString("descricao"));
                jogo.setImagemUrl(rs.getString("imagem_url"));
                return jogo;
            }

        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível buscar o jogo.", e);
        }

        return null;
    }

    public List<Jogo> listar() {
        criarTabelaSeNaoExistir();

        List<Jogo> lista = new ArrayList<>();
        String sql = "SELECT * FROM jogo ORDER BY id";

        try (Connection con = ConnectionFactory.getConexao();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Jogo jogo = new Jogo();
                jogo.setId(rs.getInt("id"));
                jogo.setNome(rs.getString("nome"));
                jogo.setExigenciaCpu(rs.getInt("exigencia_cpu"));
                jogo.setExigenciaGpu(rs.getInt("exigencia_gpu"));
                jogo.setGenero(rs.getString("genero"));
                jogo.setDescricao(rs.getString("descricao"));
                jogo.setImagemUrl(rs.getString("imagem_url"));
                lista.add(jogo);
            }

        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível listar os jogos.", e);
        }

        return lista;
    }

    public void atualizarImagem(int jogoId, String imagemUrl) {
        criarTabelaSeNaoExistir();
        String sql = "UPDATE jogo SET imagem_url = ? WHERE id = ?";

        try (Connection con = ConnectionFactory.getConexao();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, vazioComoNull(imagemUrl));
            ps.setInt(2, jogoId);
            if (ps.executeUpdate() == 0) {
                throw new DataAccessException("O jogo selecionado não foi encontrado.", null);
            }
        } catch (SQLException e) {
            throw new DataAccessException("Não foi possível atualizar a capa do jogo.", e);
        }
    }

    private String vazioComoNull(String valor) {
        return valor == null || valor.isBlank() ? null : valor.trim();
    }
}
